"use client";

import Link from "next/link";
import { ArrowLeft, Shield, Heart, AlertTriangle, Lock } from "lucide-react";

export default function TermsOfUsePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50">
      <header className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <Link
            href="/"
            className="inline-flex items-center space-x-2 text-purple-600 hover:text-purple-700 transition-colors"
          >
            <ArrowLeft className="h-5 w-5" />
            <span className="font-medium">Back to Lily Heart AI</span>
          </Link>
        </div>
      </header>

      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="bg-white rounded-2xl shadow-lg p-8">
          <div className="text-center mb-12">
            <div className="w-16 h-16 bg-gradient-to-br from-purple-600 to-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
              <Shield className="h-8 w-8 text-white" />
            </div>
            <h1
              className="text-3xl font-bold text-gray-900 mb-4"
              style={{ fontFamily: "var(--font-poppins)" }}
            >
              Terms of Use & Disclaimer
            </h1>
            <p
              className="text-lg text-gray-600"
              style={{ fontFamily: "var(--font-inter)" }}
            >
              Effective Date: {new Date().toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </p>
          </div>

          <div className="prose prose-lg max-w-none space-y-8">
            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                1. General Information
              </h2>
              <p
                className="text-gray-700 leading-relaxed"
                style={{ fontFamily: "var(--font-inter)" }}
              >
                Lily Heart AI (the "App") is an AI-based application that provides mental wellness information, emotional support prompts, and general self-help guidance. It is not a medical or mental health service, nor does it offer professional therapy, diagnosis, or treatment. The App is provided for informational and educational purposes only.
              </p>
            </section>

            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                2. No Medical or Mental Health Advice
              </h2>
              <div className="bg-red-50 border border-red-200 rounded-lg p-6 mb-4">
                <div className="flex items-start space-x-3">
                  <AlertTriangle className="h-6 w-6 text-red-600 mt-1 flex-shrink-0" />
                  <div>
                    <p
                      className="text-red-700"
                      style={{ fontFamily: "var(--font-inter)" }}
                    >
                      The App does not provide medical, psychiatric, or therapeutic services. Use of this App does not create a therapist-client, doctor-patient, or any licensed professional relationship. Content generated by the AI should not be relied upon as a substitute for qualified mental health care or professional judgment.
                    </p>
                  </div>
                </div>
              </div>
              <div className="bg-orange-50 border border-orange-200 rounded-lg p-6">
                <h3
                  className="text-lg font-semibold text-orange-800 mb-3"
                  style={{ fontFamily: "var(--font-poppins)" }}
                >
                  If you are experiencing a mental health emergency or crisis, you should immediately contact your local emergency services, a licensed mental health provider, or a crisis hotline.
                </h3>
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="bg-white rounded-lg p-4">
                    <p className="font-semibold text-gray-900">Canada</p>
                    <p className="text-gray-700">Contact Talk Suicide Canada at</p>
                    <button
                      onClick={() => window.open("tel:1-833-456-4566")}
                      className="text-blue-600 hover:text-blue-700 underline"
                    >
                      1-833-456-4566
                    </button>
                  </div>
                  <div className="bg-white rounded-lg p-4">
                    <p className="font-semibold text-gray-900">United States</p>
                    <p className="text-gray-700">Contact the Suicide & Crisis Lifeline at</p>
                    <button
                      onClick={() => window.open("tel:988")}
                      className="text-blue-600 hover:text-blue-700 underline"
                    >
                      988
                    </button>
                  </div>
                </div>
              </div>
            </section>

            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                3. No Endorsement of Professional Titles
              </h2>
              <p
                className="text-gray-700 leading-relaxed"
                style={{ fontFamily: "var(--font-inter)" }}
              >
                This App does not employ or provide access to licensed therapists, psychologists, psychiatrists, or other regulated health professionals. Any reference to "AI therapist" or similar terminology is for branding or thematic purposes only and does not imply licensure or professional qualification.
              </p>
            </section>

            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                4. User Responsibilities
              </h2>
              <p
                className="text-gray-700 leading-relaxed mb-4"
                style={{ fontFamily: "var(--font-inter)" }}
              >
                You are solely responsible for how you use the information provided by the App. You agree not to use the App as a replacement for any form of professional mental health treatment or advice.
              </p>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div className="flex items-start space-x-3">
                  <Lock className="h-5 w-5 text-blue-600 mt-1 flex-shrink-0" />
                  <div>
                    <p
                      className="text-blue-800 font-medium"
                      style={{ fontFamily: "var(--font-inter)" }}
                    >
                      Always seek the advice of a qualified provider with any questions regarding a mental health condition.
                    </p>
                  </div>
                </div>
              </div>
            </section>

            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                5. Geographic Limitations and Compliance
              </h2>
              <p
                className="text-gray-700 leading-relaxed"
                style={{ fontFamily: "var(--font-inter)" }}
              >
                This App is intended for users in Canada and the United States. We do not claim compliance with specific state or provincial laws beyond general consumer protection guidelines. If local laws require regulation or prohibit the type of service offered by this App, you agree to refrain from using it in those jurisdictions.
              </p>
            </section>

            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                6. Limitation of Liability
              </h2>
              <p
                className="text-gray-700 leading-relaxed"
                style={{ fontFamily: "var(--font-inter)" }}
              >
                We make no warranties regarding the accuracy, completeness, or usefulness of any content provided. Under no circumstances shall the developers or distributors of this App be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the App.
              </p>
            </section>

            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                7. Acceptance of Terms
              </h2>
              <p
                className="text-gray-700 leading-relaxed mb-4"
                style={{ fontFamily: "var(--font-inter)" }}
              >
                By using the App, you confirm that you have read, understood, and accepted these Terms of Use and the associated disclaimers.
              </p>
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                <p
                  className="text-yellow-800 font-medium"
                  style={{ fontFamily: "var(--font-inter)" }}
                >
                  If you do not agree to these terms, you must not use the App.
                </p>
              </div>
            </section>

            <section>
              <h2
                className="text-2xl font-bold text-gray-900 mb-4"
                style={{ fontFamily: "var(--font-poppins)" }}
              >
                8. Contact Information
              </h2>
              <p
                className="text-gray-700 leading-relaxed"
                style={{ fontFamily: "var(--font-inter)" }}
              >
                If you have questions about these Terms of Use, please contact us at:
              </p>
              <div className="bg-gray-50 rounded-lg p-4 mt-4">
                <p className="text-gray-700">
                  Email: support@lilyheart.ai
                  <br />
                  Website: https://lilyheart.ai
                  <br />
                  Support Hours: Monday - Friday, 9 AM - 6 PM EST
                </p>
              </div>
            </section>
          </div>

          <div className="border-t border-gray-200 mt-12 pt-8 text-center">
            <p
              className="text-gray-600"
              style={{ fontFamily: "var(--font-inter)" }}
            >
              By using Lily Heart AI, you acknowledge that you have read, understood, and agree to these Terms of Use and the associated disclaimers.
            </p>
            <Link
              href="/"
              className="inline-flex items-center space-x-2 text-purple-600 hover:text-purple-700 transition-colors mt-4"
            >
              <Heart className="h-5 w-5" />
              <span className="font-medium">Return to Lily Heart AI</span>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
